package io.rackshift.metal.sdk.model;

import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import java.io.Serializable;

public class Memory implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("物理机id")
    private String physicalMachineId;

    @ApiModelProperty("对应CPU编号")
    private String memCpuNum;

    @ApiModelProperty("插槽号 与CPU一起构成唯一主键 mem_cpu_num:mem_mod_num")
    private String memModNum;

    @ApiModelProperty("容量")
    private String memModSize;

    @ApiModelProperty("类型如DDR3")
    private String memModType;

    @ApiModelProperty("频率 MHz")
    private String memModFrequency;

    @ApiModelProperty("型号")
    private String memModPartNum;

    @ApiModelProperty("电压 V")
    private String memModMinVolt;

    @ApiModelProperty("序列号")
    private String sn;

    @ApiModelProperty("同步时间")
    private Long syncTime;

    @ApiModelProperty("硬件状态:0 存量，1 新增， 2 删除")
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pm_memory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.id
     *
     * @return the value of pm_memory.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.id
     *
     * @param id the value for pm_memory.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.physical_machine_id
     *
     * @return the value of pm_memory.physical_machine_id
     * @mbg.generated
     */
    public String getBareMetalId() {
        return physicalMachineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.physical_machine_id
     *
     * @param physicalMachineId the value for pm_memory.physical_machine_id
     * @mbg.generated
     */
    public void setBareMetalId(String physicalMachineId) {
        this.physicalMachineId = physicalMachineId == null ? null : physicalMachineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.mem_cpu_num
     *
     * @return the value of pm_memory.mem_cpu_num
     * @mbg.generated
     */
    public String getMemCpuNum() {
        return memCpuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.mem_cpu_num
     *
     * @param memCpuNum the value for pm_memory.mem_cpu_num
     * @mbg.generated
     */
    public void setMemCpuNum(String memCpuNum) {
        this.memCpuNum = memCpuNum == null ? null : memCpuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.mem_mod_num
     *
     * @return the value of pm_memory.mem_mod_num
     * @mbg.generated
     */
    public String getMemModNum() {
        return memModNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.mem_mod_num
     *
     * @param memModNum the value for pm_memory.mem_mod_num
     * @mbg.generated
     */
    public void setMemModNum(String memModNum) {
        this.memModNum = memModNum == null ? null : memModNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.mem_mod_size
     *
     * @return the value of pm_memory.mem_mod_size
     * @mbg.generated
     */
    public String getMemModSize() {
        return memModSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.mem_mod_size
     *
     * @param memModSize the value for pm_memory.mem_mod_size
     * @mbg.generated
     */
    public void setMemModSize(String memModSize) {
        this.memModSize = memModSize == null ? null : memModSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.mem_mod_type
     *
     * @return the value of pm_memory.mem_mod_type
     * @mbg.generated
     */
    public String getMemModType() {
        return memModType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.mem_mod_type
     *
     * @param memModType the value for pm_memory.mem_mod_type
     * @mbg.generated
     */
    public void setMemModType(String memModType) {
        this.memModType = memModType == null ? null : memModType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.mem_mod_frequency
     *
     * @return the value of pm_memory.mem_mod_frequency
     * @mbg.generated
     */
    public String getMemModFrequency() {
        return memModFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.mem_mod_frequency
     *
     * @param memModFrequency the value for pm_memory.mem_mod_frequency
     * @mbg.generated
     */
    public void setMemModFrequency(String memModFrequency) {
        this.memModFrequency = memModFrequency == null ? null : memModFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.mem_mod_part_num
     *
     * @return the value of pm_memory.mem_mod_part_num
     * @mbg.generated
     */
    public String getMemModPartNum() {
        return memModPartNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.mem_mod_part_num
     *
     * @param memModPartNum the value for pm_memory.mem_mod_part_num
     * @mbg.generated
     */
    public void setMemModPartNum(String memModPartNum) {
        this.memModPartNum = memModPartNum == null ? null : memModPartNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.mem_mod_min_volt
     *
     * @return the value of pm_memory.mem_mod_min_volt
     * @mbg.generated
     */
    public String getMemModMinVolt() {
        return memModMinVolt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.mem_mod_min_volt
     *
     * @param memModMinVolt the value for pm_memory.mem_mod_min_volt
     * @mbg.generated
     */
    public void setMemModMinVolt(String memModMinVolt) {
        this.memModMinVolt = memModMinVolt == null ? null : memModMinVolt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.sn
     *
     * @return the value of pm_memory.sn
     * @mbg.generated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.sn
     *
     * @param sn the value for pm_memory.sn
     * @mbg.generated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.sync_time
     *
     * @return the value of pm_memory.sync_time
     * @mbg.generated
     */
    public Long getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.sync_time
     *
     * @param syncTime the value for pm_memory.sync_time
     * @mbg.generated
     */
    public void setSyncTime(Long syncTime) {
        this.syncTime = syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_memory.status
     *
     * @return the value of pm_memory.status
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_memory.status
     *
     * @param status the value for pm_memory.status
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}